/*
 * TIMER.c
 *
 * Created: 7/1/2023 5:00:34 PM
 *  Author: iot05
 */ 

#include "TIMER0.h"

void SET_TIMER0_MODE(TIMER_MODE WGM){
	switch (WGM)
	{
		case DISCONNECTED:
			CLEARBIT(TCCR0,WGM00);
			CLEARBIT(TCCR0,WGM01);
		break;
		case PHASE_CORRECT:
			SETBIT(TCCR0,WGM00);
			CLEARBIT(TCCR0,WGM01);
		break;
		case CTC:
			CLEARBIT(TCCR0,WGM00);
			SETBIT(TCCR0,WGM01);
		break;
		case FAST_PWM:
			SETBIT(TCCR0,WGM00);
			SETBIT(TCCR0,WGM01);
		break;
	}
}
void SET_WAVE_MODE_NON_PWM(WAVE_MODE_NON_PWM COM){
		switch(COM){
			case DISCONNECTED:
				CLEARBIT(TCCR0,COM00);
				CLEARBIT(TCCR0,COM01);
			break;
			case TOGGLE:
				SETBIT(TCCR0,COM00);
				CLEARBIT(TCCR0,COM01);
			break;
			case CLEAR:
				CLEARBIT(TCCR0,COM00);
				SETBIT(TCCR0,COM01);
			break;
			case SET:
				SETBIT(TCCR0,COM00);
				SETBIT(TCCR0,COM01);
			break;
		}
}
void SET_WAVE_MODE(WAVE_MODE COM){
	switch(COM){
		case DISCONNECTED:
			CLEARBIT(TCCR0,COM00);
			CLEARBIT(TCCR0,COM01);
		break;
		case NON_INVERTING:
			CLEARBIT(TCCR0,COM00);
			SETBIT(TCCR0,COM01);
		break;
		case INVERTING:
			SETBIT(TCCR0,COM00);
			SETBIT(TCCR0,COM01);
		break;
	}
}
void SET_PRESCALLER_MODE(PRESCALLER_MODE CS){
	switch(CS){
		case STOPPED:
			CLEARBIT(TCCR0,CS00);
			CLEARBIT(TCCR0,CS01);
			CLEARBIT(TCCR0,CS02);
		break;
		case NO_PRESCALLING:
			SETBIT(TCCR0,CS00);
			CLEARBIT(TCCR0,CS01);
			CLEARBIT(TCCR0,CS02);
		break;
		case CLK_8:
			CLEARBIT(TCCR0,CS00);
			SETBIT(TCCR0,CS01);
			CLEARBIT(TCCR0,CS02);
		break;
		case CLK_64:
			SETBIT(TCCR0,CS00);
			SETBIT(TCCR0,CS01);
			CLEARBIT(TCCR0,CS02);
		break;
		case CLK_256:
			CLEARBIT(TCCR0,CS00);
			CLEARBIT(TCCR0,CS01);
			SETBIT(TCCR0,CS02);
		break;
		case CLK_1024:
			SETBIT(TCCR0,CS00);
			CLEARBIT(TCCR0,CS01);
			SETBIT(TCCR0,CS02);
		break;
		case EXT_CLK_FALLING_EDGE:
			CLEARBIT(TCCR0,CS00);
			SETBIT(TCCR0,CS01);
			SETBIT(TCCR0,CS02);
		break;
		case EXT_CLK_RISING_EDGE:
			SETBIT(TCCR0,CS00);
			SETBIT(TCCR0,CS01);
			SETBIT(TCCR0,CS02);
		break;
		
	}
}